WORD_LIST = [
"ability","absence","academy","account","action","actor","actress","activity","addition","address",
"advice","affair","agency","agenda","agreement","airport","alarm","album","alcohol","alert",
"alien","alley","alliance","amount","analysis","animal","answer","anxiety","apology","appeal",
"apple","april","arch","area","argument","army","arrival","article","artist","aspect",
"assignment","assistant","athlete","attempt","attention","attitude","audience","author","average","award",
"baby","background","balance","ball","banana","band","bank","bar","base","basket",
"battle","beach","bear","beauty","bedroom","beer","beginning","behavior","belief","bell",
"belt","bench","benefit","berry","bicycle","bill","bird","birth","birthday","biscuit",
"blade","blanket","block","blood","board","boat","body","bonus","book","border",
"bottle","bottom","bowl","box","boy","brain","branch","bread","breakfast","bridge",
"brother","budget","building","bullet","bunch","bus","business","butter","button","buyer",

"cabin","cable","cake","camera","camp","campaign","canal","cancer","candidate","candle",
"cannon","canvas","capital","captain","car","carbon","card","career","carpet","carrot",
"castle","casual","catalog","category","cause","ceiling","celebration","cell","center","century",
"ceremony","chain","chair","challenge","champion","chance","change","channel","chapter","character",
"charge","charity","charm","chart","check","cheese","chef","cherry","chest","chicken",
"chief","child","choice","church","circle","city","claim","class","clerk","client",
"climate","clock","closet","cloud","club","clue","coach","coal","coast","coffee",
"coin","collection","college","color","column","combination","comfort","command","comment","committee",

"company","comparison","competition","complaint","complex","concept","concern","concert","condition","conference",
"confidence","conflict","connection","consequence","construction","contact","contest","context","contract","control",
"conversation","cookie","copy","corner","cost","cotton","couch","country","course","court",
"cousin","cover","craft","credit","crew","crime","crisis","critic","crowd","culture",
"cup","currency","customer","cycle","damage","dance","danger","data","daughter","day",
"dealer","debate","debt","decision","decline","default","defense","degree","delay","delivery",
"demand","department","departure","deposit","depth","description","design","desk","detail","development",

"device","diamond","diet","difference","difficulty","dinner","direction","director","dirt","disaster",
"discipline","discount","discussion","disease","display","distance","district","doctor","document","dog",
"dollar","domain","door","double","draft","drama","drawer","dream","dress","driver",
"drop","drug","drum","duck","dust","duty","eagle","ear","earth","economy",
"edge","editor","education","effect","effort","egg","election","element","elevator","emotion",
"emphasis","employee","employer","energy","engine","engineer","entertainment","enthusiasm","entrance","entry",

"environment","episode","equipment","error","escape","essay","estate","estimate","ethics","event",
"example","exchange","exercise","exhibit","expense","experience","expert","explanation","expression","extension",
"eye","face","fact","factor","failure","family","farm","fashion","father","feature",
"feedback","festival","field","figure","film","filter","finance","finding","finger","finish",
"fire","firm","fish","flight","floor","flower","focus","food","football","force",
"forest","fortune","foundation","frame","freedom","friend","front","fruit","fuel","function",
"fund","future","gallery","game","garage","garden","gas","gate","gear","gene",
"gift","girl","glass","goal","gold","golf","government","grade","grain","grandfather",
"grandmother","grass","growth","guard","guest","guide","guitar","habit","hair","half",

"hall","hand","handle","happiness","harbor","hardware","harm","hat","health","hearing",
"heart","heat","height","hero","history","holiday","home","honey","honor","hope",
"horse","hospital","host","hotel","hour","house","human","humor","idea","identity",
"image","impact","importance","impression","improvement","incident","income","increase","industry","information",
"initiative","injury","innovation","input","inspection","inspiration","instance","instruction","insurance","intention",
"interaction","interest","internet","interview","introduction","invention","investment","issue","item","jacket",
"january","jazz","jewel","job","journal","journey","judge","juice","july","jump",
"jungle","junior","jury","justice","keyboard","kick","kid","king","kitchen","knowledge",
"label","labor","ladder","lake","lamp","language","laptop","laser","laugh","law",
"layer","leader","league","learning","leather","lecture","leg","legend","length","lesson",
"letter","level","library","life","light","limit","line","link","lion","liquid",

"list","literature","location","lock","logic","loss","love","machine","magazine","magic",
"mail","main","maintenance","major","manager","market","marriage","material","math","matter",
"maximum","meal","meaning","measurement","meat","mechanism","media","medicine","member","memory",
"mention","menu","message","metal","method","middle","midnight","milk","mind","minimum",
"minister","minute","mirror","mission","mistake","mixture","mobile","mode","model","moment",
"money","monitor","month","mood","morning","mother","motion","motor","mountain","mouse",
"mouth","movie","music","mystery","name","nation","nature","navigation","neck","need",
"negotiation","network","news","night","noise","normal","note","notion","novel","number",
"object","observation","occasion","office","officer","operation","opinion","opportunity","option","orange",
"order","organization","outcome","output","owner","oxygen","package","page","pain","painting",
"paper","parent","park","partner","party","passage","passenger","passion","password","patient",
"pattern","payment","peace","pen","pencil","people","performance","period","permission","person",
"phase","phone","photo","physics","piano","picture","piece","pilot","pitch","place",
"plan","planet","platform","player","pleasure","plot","pocket","poem","poet","point",
"policy","pool","population","position","possibility","post","potato","power","practice","preference",
"preparation","presence","presentation","pressure","price","pride","primary","principle","print","priority",
"prison","problem","process","producer","product","production","profession","profile","profit","program",
"progress","project","promise","property","proposal","protection","protein","protest","protocol","psychology",
"public","purpose","quality","quantity","quarter","queen","question","queue","race","radio",
"rain","range","rate","reaction","reading","reality","reason","recipe","recognition","recommendation",
"record","recovery","reflection","region","register","relationship","release","reputation","request","research",
"resolution","resource","response","restaurant","result","retail","revenue","review","revolution","reward",
"rhythm","rice","river","road","robot","role","room","routine","rule","safety",
"salary","sample","satisfaction","science","screen","search","season","seat","secret","section",
"security","selection","self","sense","series","service","session","setting","shadow","shape",
"share","sheet","shelter","shift","ship","shirt","shock","shoe","shop","signal",
"signature","silence","silver","similarity","singer","sister","situation","skill","sleep","smile",
"society","software","solution","song","sound","source","space","speaker","special","speech",
"speed","spirit","sport","spring","square","stage","standard","star","state","statement",
"station","status","step","stock","storage","story","strategy","street","strength","structure",
"student","studio","study","style","subject","success","suggestion","summer","supply","support",
"surface","surprise","survey","system","table","tactic","talent","target","task","taste",
"tax","teacher","team","technology","temperature","term","theory","thing","thought","ticket",
"time","tissue","title","tool","topic","total","touch","tour","tower","track",
"trade","tradition","traffic","training","transport","travel","treasure","treatment","tree","trend",
"trial","truth","tune","type","union","unit","university","user","value","variation",
"vehicle","version","video","view","village","vision","visit","voice","volume","wait",
"warning","water","wealth","weather","web","wedding","week","weight","window","winner",
"winter","wire","wisdom","woman","wood","word","work","worker","world","writer",
"year","youth","zone"
]


easy_words = [w for w in WORD_LIST if len(w) <= 5]
medium_words = [w for w in WORD_LIST if 6 <= len(w) <= 8]
hard_words = [w for w in WORD_LIST if len(w) > 8]